CREATE TYPE [dbo].[Int64IdsList] AS TABLE([Id] [BIGINT] NOT NULL)

CREATE TYPE [dbo].[Int32IdsList] AS TABLE([Id] [INT] NOT NULL)

CREATE TYPE [dbo].[Int16IdsList] AS TABLE([Id] [SMALLINT] NOT NULL)

CREATE TYPE [dbo].[GuidIdsList] AS TABLE([Id] [UNIQUEIDENTIFIER] NOT NULL)